---
- name: Create .neovim directory
  file:
    path: '{{ neovim_path }}'
    state: directory

- name: Install all dependencies
  apt:
    pkg: '{{ neovim_deps_list }}'
    state: latest
    update_cache: yes

- name: Copy neovim install script
  copy:
    src: install-neovim.sh
    dest: '{{ neovim_path }}'
    mode: '0711'
  register: script_out

- name: Install neovim from binaries
  shell: '{{ script_out.dest }} {{ home_path }} {{ neovim_path }}'
