---

- name: Uninstall .neovim directory
  file:
    path: '{{ neovim_path }}'
    state: absent

- name: Uninstall all dependencies
  apt:
    pkg: '{{ neovim_deps_list }}'
    state: absent
    update_cache: yes

- name: Remove neovim installed binaries
  file:
    path: '{{ item }}'
    state: absent
  loop:
  - '/usr/local/bin/nvim'
  - '/usr/local/share/nvim/'
