---
- name: '[{{ submodule }}] Create .kitty directory'
  file:
    path: '{{ kitty_path }}'
    state: directory

- name: '[{{ submodule }}] Copy kitty install script'
  copy:
    src: install-kitty.sh
    dest: '{{ kitty_path }}'
    mode: '0711'
  register: script_out

- name: '[{{ submodule }}] Install kitty from binaries'
  shell: '{{ script_out.dest }} {{ home_path }} {{ kitty_desktop_path }}'
