---

- name: Uninstall / Install packages
  import_tasks: packages/main.yaml

- name: Uninstall / Install dotfiles
  import_tasks: dotfiles/main.yaml

- name: Uninstall / Install kitty
  import_tasks: kitty/main.yaml

- name: Uninstall / Install neovim
  import_tasks: neovim/main.yaml
