---

- name: Check vim existence
  shell: 'which vim'
  register: vim
  ignore_errors: yes
  tags: always

- name: Install vim
  block:
  - name: download package
    package:
      name: vim
      state: latest
  become: yes
  when: vim.rc != 0
  tags: [ install ]

- name: Uninstall vim
  block:
  - name: remove package
    package:
      name: vim
      state: absent
  become: yes
  when: vim.rc == 0
  tags: [ uninstall ]
